abs/booking/urls.py
from django.urls import path

from .endpoints import BookingTaskEndpoint
from .views import BookingTasksView, CreateBookingTaskView, GetBookingFormView, GetPersonFormView, \
    BookingTasksTableView, BookingObjectTaskErrorDetailView, GetInsuranceFormView, RenderInsuranceTemplate

app_name = 'booking'
urlpatterns = [
    path('', BookingTasksView.as_view(), name='booking_tasks'),
    path('tasks/table/', BookingTasksTableView.as_view(), name='booking_tasks_table'),
    path('add/', CreateBookingTaskView.as_view(), name='create_booking_task'),
    path('create/task/', BookingTaskEndpoint.as_view(), name='create_task'),
    path('get/person/form/', GetPersonFormView.as_view(), name='get_person_form'),
    path('get/booking/form/', GetBookingFormView.as_view(), name='get_booking_form'),
    path('get/insurance/form/', GetInsuranceFormView.as_view(), name='get_insurance_form'),
    path('render/insurance/template/<int:pk>/', RenderInsuranceTemplate.as_view(), name='render_insurance_template'),
    path('booking/object/<int:ct>/<int:pk>/',
         BookingObjectTaskErrorDetailView.as_view(),
         name='booking_object_task_errors_detail'),
]

abs/users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("", view=views.UserListView.as_view(), name="list"),
    path("~redirect/", view=views.UserRedirectView.as_view(), name="redirect"),
    path("~update/", view=views.UserUpdateView.as_view(), name="update"),
    path(
        "<str:username>",
        view=views.UserDetailView.as_view(),
        name="detail",
    ),
]

config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView
from django.views import defaults as default_views

urlpatterns = [
    path("", RedirectView.as_view(url='booking/'), name="home"),
    path(
        "booking/",
        include("abs.booking.urls", namespace="booking"),
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("abs.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

abs/booking/models/account.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

from ..booking_registry import bookingRegistry


class BookingAccount(models.Model):
    username = models.CharField(max_length=50, blank=True)
    email = models.EmailField()
    password = models.CharField(max_length=50, blank=True)
    is_active = models.BooleanField(default=True)

    booking_site = models.CharField(max_length=50, choices=bookingRegistry.as_choices(), blank=True)

    created_at = models.DateTimeField(auto_now_add=True, editable=False)

    def __str__(self):
        return f'Account {self.email} {self.content_type}'

abs/booking/models/biletix_flight.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.utils.translation import ugettext_lazy as _

from .booking_base import BookingBase


class BiletixFlight(BookingBase):
    city_from = models.CharField(max_length=255)
    city_to = models.CharField(max_length=255)
    date_from = models.DateField()
    date_to = models.DateField()
    ticket = models.FileField(upload_to='biletix_flight', null=True, blank=True)

    def get_html_info(self):
        return f'<b>Biletix</b><br>' \
               f'{self.city_from} -> {self.city_to}<br>' \
               f'{self.date_from} - {self.date_to}<br>' \
               f'{"<br>".join([person.get_html_info() for person in self.persons.all()])}'

    def get_results_html_info(self):
        if self.ticket:
            return f'<a href="{self.ticket.url}" target="_blank">Flight ticket</a>'
        return ''

abs/booking/models/booking_base.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.utils.translation import ugettext_lazy as _


class BookingBase(models.Model):
    TASK_IN_QUEUE_STATUS = 0
    TASK_IN_PROGRESS_STATUS = 1
    TASK_FAILED_STATUS = 2
    TASK_SUCCESS_STATUS = 3

    STATUS_CHOICES = (
        (TASK_IN_QUEUE_STATUS, _(u'In queue')),
        (TASK_IN_PROGRESS_STATUS, _(u'In progress')),
        (TASK_FAILED_STATUS, _(u'Failed')),
        (TASK_SUCCESS_STATUS, _(u'Success')),
    )
    booking_task = models.ForeignKey('booking.BookingTask', on_delete=models.CASCADE)
    status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES,
                                              default=TASK_IN_QUEUE_STATUS)
    session_id = models.CharField(max_length=255, blank=True)
    persons = GenericRelation('booking.Person')
    task_errors = GenericRelation('booking.TaskError')
    created_at = models.DateTimeField(auto_now_add=True, editable=False)

    class Meta:
        abstract = True

abs/booking/models/booking_home.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.utils.translation import ugettext_lazy as _

from .booking_base import BookingBase


class BookingHome(BookingBase):
    city = models.CharField(max_length=255)
    date_from = models.DateField()
    date_to = models.DateField()
    ticket = models.FileField(upload_to='booking_home', null=True, blank=True)
    booking_confirmation_url = models.TextField(blank=True)

    def get_html_info(self):
        return f'<b>Booking.com</b><br>' \
               f'{self.city}<br>' \
               f'{self.date_from} - {self.date_to}<br>' \
               f'{"<br>".join([person.get_html_info() for person in self.persons.all()])}'

    def get_results_html_info(self):
        if self.ticket and self.booking_confirmation_url:
            return f'<a href="{self.ticket.url}" target="_blank">Confirmation pdf</a><br>' \
                   f'<a href="{self.booking_confirmation_url}" target="_blank">Confirmation link</a>'
        return ''

abs/booking/models/booking_task.py
from django.db import models
from django.contrib.postgres.fields import JSONField
from django.utils.translation import ugettext_lazy as _


class BookingTask(models.Model):
    user = models.ForeignKey('users.User', verbose_name=_('User'), help_text=_('Task owner'), on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)

abs/booking/forms/biletix_flight.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms import layout

from ..models import BiletixFlight
from ..booking_registry import bookingRegistry


class BiletixFlightForm(forms.ModelForm):
    key_name = forms.ChoiceField(choices=bookingRegistry.as_choices(),
                                 widget=forms.HiddenInput(),
                                 initial='Biletix')
    city_from = forms.ChoiceField(choices=(('Москва', 'Москва'), ), initial='Москва')

    def __init__(self, *args, **kwargs):
        super(BiletixFlightForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = layout.Layout(
            'key_name',
            layout.Div(
                layout.Div(
                    'city_from',
                    css_class='col-6'
                ),
                layout.Div(
                    'city_to',
                    css_class='col-6'
                ),
                css_class='row'
            ),
            layout.Div(
              layout.HTML('Dates*')
            ),
            layout.Div(
                layout.Field('date_from', css_class='form-control', template='crispy_forms/input_without_wrapper.html'),
                layout.HTML('<span class="input-group-addon">to</span>'),
                layout.Field('date_to', css_class='form-control', template='crispy_forms/input_without_wrapper.html'),
                css_class='input-daterange input-group'
            )
        )

    class Meta:
        model = BiletixFlight
        exclude = ('ticket', 'booking_task', 'status')

abs/booking/forms/booking_home.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms import layout

from ..models import BookingHome
from ..booking_registry import bookingRegistry


class BookingHomeForm(forms.ModelForm):
    key_name = forms.ChoiceField(choices=bookingRegistry.as_choices(),
                                 widget=forms.HiddenInput(),
                                 initial='Booking')

    def __init__(self, *args, **kwargs):
        super(BookingHomeForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = layout.Layout(
            'key_name',
            'city',
            layout.Div(
              layout.HTML('Dates*')
            ),
            layout.Div(
                layout.Field('date_from', css_class='form-control', template='crispy_forms/input_without_wrapper.html'),
                layout.HTML('<span class="input-group-addon">to</span>'),
                layout.Field('date_to', css_class='form-control', template='crispy_forms/input_without_wrapper.html'),
                css_class='input-daterange input-group'
            )
        )

    class Meta:
        model = BookingHome
        exclude = ('booking_task', 'status', 'booking_confirmation_url', 'ticket')

abs/booking/forms/insurance.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms import layout

from ..models import Insurance


class InsuranceForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(InsuranceForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = layout.Layout(
            layout.Div(
                layout.Div(
                    'company',
                    css_class='col-4'
                ),
                layout.Div(
                    'policyholder',
                    css_class='col-4'
                ),
                layout.Div(
                    'issue_date',
                    css_class='col-4'
                ),
                css_class='row'
            ),
            layout.Div(
              layout.HTML('Dates*')
            ),
            layout.Div(
                layout.Field('date_from', css_class='form-control', template='crispy_forms/input_without_wrapper.html'),
                layout.HTML('<span class="input-group-addon">to</span>'),
                layout.Field('date_to', css_class='form-control', template='crispy_forms/input_without_wrapper.html'),
                css_class='input-daterange input-group'
            )
        )

    class Meta:
        model = Insurance
        exclude = ('insurance_file', )

abs/booking/forms/klm_flight.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms import layout

from ..models import KLMFlight
from ..booking_registry import bookingRegistry


class KLMFlightForm(forms.ModelForm):
    key_name = forms.ChoiceField(choices=bookingRegistry.as_choices(),
                                 widget=forms.HiddenInput(),
                                 initial='KLM')
    city_from = forms.ChoiceField(choices=(('Москва', 'Москва'), ), initial='Москва')

    def __init__(self, *args, **kwargs):
        super(KLMFlightForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = layout.Layout(
            'key_name',
            layout.Div(
                layout.Div(
                    'city_from',
                    css_class='col-6'
                ),
                layout.Div(
                    'city_to',
                    css_class='col-6'
                ),
                css_class='row'
            ),
            layout.Div(
              layout.HTML('Dates*')
            ),
            layout.Div(
                layout.Field('date_from', css_class='form-control', template='crispy_forms/input_without_wrapper.html'),
                layout.HTML('<span class="input-group-addon">to</span>'),
                layout.Field('date_to', css_class='form-control', template='crispy_forms/input_without_wrapper.html'),
                css_class='input-daterange input-group'
            )
        )

    class Meta:
        model = KLMFlight
        exclude = ('ticket', 'booking_task', 'status')

abs/booking/forms/ostrovok_home.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms import layout

from ..models import OstrovokHome
from ..booking_registry import bookingRegistry


class OstrovokHomeForm(forms.ModelForm):
    key_name = forms.ChoiceField(choices=bookingRegistry.as_choices(),
                                 widget=forms.HiddenInput(),
                                 initial='Ostrovok')

    def __init__(self, *args, **kwargs):
        super(OstrovokHomeForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = layout.Layout(
            'key_name',
            'city',
            layout.Div(
              layout.HTML('Dates*')
            ),
            layout.Div(
                layout.Field('date_from', css_class='form-control', template='crispy_forms/input_without_wrapper.html'),
                layout.HTML('<span class="input-group-addon">to</span>'),
                layout.Field('date_to', css_class='form-control', template='crispy_forms/input_without_wrapper.html'),
                css_class='input-daterange input-group'
            )
        )

    class Meta:
        model = OstrovokHome
        exclude = ('booking_task', 'status', 'booking_confirmation_url', 'booking_print_url')

abs/booking/forms/person.py
import datetime
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms import layout, bootstrap

from ..models import Person


class PersonForm(forms.ModelForm):
    date_of_birth = forms.DateField(required=False, widget=forms.SelectDateWidget(
        years=range(1940, datetime.date.today().year),
        attrs=({'style': 'width: 33%; display: inline-block;'})
    ))

    def __init__(self, *args, **kwargs):
        super(PersonForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = layout.Layout(
            layout.Div(
                layout.Div(
                    'first_name',
                    css_class='col-5'
                ),
                layout.Div(
                    'last_name',
                    css_class='col-5'
                ),
                layout.Div(
                    'gender',
                    css_class='col-2'
                ),
                css_class='row'
            ),
            layout.Div(
                layout.Div(
                    'date_of_birth',
                    css_class='col-5 date_of_birth_row'
                ),
                css_class='row'
            )
        )

    class Meta:
        model = Person
        exclude = ('content_object', 'content_type', 'object_id')

abs/booking/forms/s7_flight.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms import layout

from ..models import S7Flight
from ..booking_registry import bookingRegistry


class S7FlightForm(forms.ModelForm):
    key_name = forms.ChoiceField(choices=bookingRegistry.as_choices(),
                                 widget=forms.HiddenInput(),
                                 initial='S7')
    city_from = forms.ChoiceField(choices=(('Москва', 'Москва'), ), initial='Москва')

    def __init__(self, *args, **kwargs):
        super(S7FlightForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = layout.Layout(
            'key_name',
            layout.Div(
                layout.Div(
                    'city_from',
                    css_class='col-6'
                ),
                layout.Div(
                    'city_to',
                    css_class='col-6'
                ),
                css_class='row'
            ),
            layout.Div(
              layout.HTML('Dates*')
            ),
            layout.Div(
                layout.Field('date_from', css_class='form-control', template='crispy_forms/input_without_wrapper.html'),
                layout.HTML('<span class="input-group-addon">to</span>'),
                layout.Field('date_to', css_class='form-control', template='crispy_forms/input_without_wrapper.html'),
                css_class='input-daterange input-group'
            )
        )

    class Meta:
        model = S7Flight
        exclude = ('ticket', 'booking_task', 'status')

abs/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

abs/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Auto Booking System{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}

        <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
              integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M"
              crossorigin="anonymous">


        <!-- Your stuff: Third-party CSS libraries go here -->

        <!-- This file stores project-specific CSS -->

        <link href="{% static 'css/project.css' %}" rel="stylesheet">


    {% endblock %}

</head>

<body>

<div class="m-b-1">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'booking:booking_tasks' %}">Auto Booking System</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {% if request.user.is_authenticated %}
                  {% url 'booking:booking_tasks' as booking_tasks_url %}
                  <li class="nav-item{% if request.path == booking_tasks_url %} active{% endif %}">
                      <a class="nav-link" href="{{ booking_tasks_url }}">Task list</a>
                  </li>
{#                    {% url 'users:detail' request.user.username as user_detail_url %}#}
{#                    <li class="nav-item{% if request.path == user_detail_url %} active{% endif %}">#}
                        {# URL provided by django-allauth/account/urls.py #}
{#                        <a class="nav-link"#}
{#                           href="{{ user_detail_url }}">{% trans "My Profile" %}</a>#}
{#                    </li>#}
                    {% if request.user.is_superuser %}
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'admin:index' %}">Admin panel</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        {# URL provided by django-allauth/account/urls.py #}
                        <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
                    </li>
                {% else %}
                    {% url 'account_login' as account_login_url %}
                    <li class="nav-item{% if request.path == account_login_url %} active{% endif %}">
                        {# URL provided by django-allauth/account/urls.py #}
                        <a id="log-in-link" class="nav-link" href="{{ account_login_url }}">{% trans "Sign In" %}</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

</div>

<div class="container">

    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
        {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock content %}

</div> <!-- /container -->

{% block modal %}{% endblock modal %}

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{% block javascript %}

    <!-- Required by Bootstrap v4 beta -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
            integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
            integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
            crossorigin="anonymous"></script>

    <!-- Your stuff: Third-party javascript libraries go here -->

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>

    <!-- place project specific Javascript in this file -->

    <script src="{% static 'js/project.js' %}"></script>


{% endblock javascript %}
</body>
</html>