abs/booking/urls.py
from django.urls import path

from .endpoints import BookingTaskEndpoint
from .views import BookingTasksView, CreateBookingTaskView, GetBookingFormView, GetPersonFormView, \
    BookingTasksTableView, BookingObjectTaskErrorDetailView, GetInsuranceFormView, RenderInsuranceTemplate

app_name = 'booking'
urlpatterns = [
    path('', BookingTasksView.as_view(), name='booking_tasks'),
    path('tasks/table/', BookingTasksTableView.as_view(), name='booking_tasks_table'),
    path('add/', CreateBookingTaskView.as_view(), name='create_booking_task'),
    path('create/task/', BookingTaskEndpoint.as_view(), name='create_task'),
    path('get/person/form/', GetPersonFormView.as_view(), name='get_person_form'),
    path('get/booking/form/', GetBookingFormView.as_view(), name='get_booking_form'),
    path('get/insurance/form/', GetInsuranceFormView.as_view(), name='get_insurance_form'),
    path('render/insurance/template/<int:pk>/', RenderInsuranceTemplate.as_view(), name='render_insurance_template'),
    path('booking/object/<int:ct>/<int:pk>/',
         BookingObjectTaskErrorDetailView.as_view(),
         name='booking_object_task_errors_detail'),
]

abs/users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("", view=views.UserListView.as_view(), name="list"),
    path("~redirect/", view=views.UserRedirectView.as_view(), name="redirect"),
    path("~update/", view=views.UserUpdateView.as_view(), name="update"),
    path(
        "<str:username>",
        view=views.UserDetailView.as_view(),
        name="detail",
    ),
]

config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView
from django.views import defaults as default_views

urlpatterns = [
    path("", RedirectView.as_view(url='booking/'), name="home"),
    path(
        "booking/",
        include("abs.booking.urls", namespace="booking"),
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("abs.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

abs/booking/models/account.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

from ..booking_registry import bookingRegistry


class BookingAccount(models.Model):
    username = models.CharField(max_length=50, blank=True)
    email = models.EmailField()
    password = models.CharField(max_length=50, blank=True)
    is_active = models.BooleanField(default=True)

    booking_site = models.CharField(max_length=50, choices=bookingRegistry.as_choices(), blank=True)

    created_at = models.DateTimeField(auto_now_add=True, editable=False)

    def __str__(self):
        return f'Account {self.email} {self.content_type}'

abs/booking/models/biletix_flight.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.utils.translation import ugettext_lazy as _

from .booking_base import BookingBase


class BiletixFlight(BookingBase):
    city_from = models.CharField(max_length=255)
    city_to = models.CharField(max_length=255)
    date_from = models.DateField()
    date_to = models.DateField()
    ticket = models.FileField(upload_to='biletix_flight', null=True, blank=True)

    def get_html_info(self):
        return f'<b>Biletix</b><br>' \
               f'{self.city_from} -> {self.city_to}<br>' \
               f'{self.date_from} - {self.date_to}<br>' \
               f'{"<br>".join([person.get_html_info() for person in self.persons.all()])}'

    def get_results_html_info(self):
        if self.ticket:
            return f'<a href="{self.ticket.url}" target="_blank">Flight ticket</a>'
        return ''

abs/booking/models/booking_base.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.utils.translation import ugettext_lazy as _


class BookingBase(models.Model):
    TASK_IN_QUEUE_STATUS = 0
    TASK_IN_PROGRESS_STATUS = 1
    TASK_FAILED_STATUS = 2
    TASK_SUCCESS_STATUS = 3

    STATUS_CHOICES = (
        (TASK_IN_QUEUE_STATUS, _(u'In queue')),
        (TASK_IN_PROGRESS_STATUS, _(u'In progress')),
        (TASK_FAILED_STATUS, _(u'Failed')),
        (TASK_SUCCESS_STATUS, _(u'Success')),
    )
    booking_task = models.ForeignKey('booking.BookingTask', on_delete=models.CASCADE)
    status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES,
                                              default=TASK_IN_QUEUE_STATUS)
    session_id = models.CharField(max_length=255, blank=True)
    persons = GenericRelation('booking.Person')
    task_errors = GenericRelation('booking.TaskError')
    created_at = models.DateTimeField(auto_now_add=True, editable=False)

    class Meta:
        abstract = True

abs/booking/models/booking_home.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.utils.translation import ugettext_lazy as _

from .booking_base import BookingBase


class BookingHome(BookingBase):
    city = models.CharField(max_length=255)
    date_from = models.DateField()
    date_to = models.DateField()
    ticket = models.FileField(upload_to='booking_home', null=True, blank=True)
    booking_confirmation_url = models.TextField(blank=True)

    def get_html_info(self):
        return f'<b>Booking.com</b><br>' \
               f'{self.city}<br>' \
               f'{self.date_from} - {self.date_to}<br>' \
               f'{"<br>".join([person.get_html_info() for person in self.persons.all()])}'

    def get_results_html_info(self):
        if self.ticket and self.booking_confirmation_url:
            return f'<a href="{self.ticket.url}" target="_blank">Confirmation pdf</a><br>' \
                   f'<a href="{self.booking_confirmation_url}" target="_blank">Confirmation link</a>'
        return ''

abs/booking/models/booking_task.py
from django.db import models
from django.contrib.postgres.fields import JSONField
from django.utils.translation import ugettext_lazy as _


class BookingTask(models.Model):
    user = models.ForeignKey('users.User', verbose_name=_('User'), help_text=_('Task owner'), on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)

abs/booking/forms/biletix_flight.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms import layout

from ..models import BiletixFlight
from ..booking_registry import bookingRegistry


class BiletixFlightForm(forms.ModelForm):
    key_name = forms.ChoiceField(choices=bookingRegistry.as_choices(),
                                 widget=forms.HiddenInput(),
                                 initial='Biletix')
    city_from = forms.ChoiceField(choices=(('Москва', 'Москва'), ), initial='Москва')

    def __init__(self, *args, **kwargs):
        super(BiletixFlightForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = layout.Layout(
            'key_name',
            layout.Div(
                layout.Div(
                    'city_from',
                    css_class='col-6'
                ),
                layout.Div(
                    'city_to',
                    css_class='col-6'
                ),
                css_class='row'
            ),
            layout.Div(
              layout.HTML('Dates*')
            ),
            layout.Div(
                layout.Field('date_from', css_class='form-control', template='crispy_forms/input_without_wrapper.html'),
                layout.HTML('<span class="input-group-addon">to</span>'),
                layout.Field('date_to', css_class='form-control', template='crispy_forms/input_without_wrapper.html'),
                css_class='input-daterange input-group'
            )
        )

    class Meta:
        model = BiletixFlight
        exclude = ('ticket', 'booking_task', 'status')

abs/booking/forms/booking_home.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms import layout

from ..models import BookingHome
from ..booking_registry import bookingRegistry


class BookingHomeForm(forms.ModelForm):
    key_name = forms.ChoiceField(choices=bookingRegistry.as_choices(),
                                 widget=forms.HiddenInput(),
                                 initial='Booking')

    def __init__(self, *args, **kwargs):
        super(BookingHomeForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = layout.Layout(
            'key_name',
            'city',
            layout.Div(
              layout.HTML('Dates*')
            ),
            layout.Div(
                layout.Field('date_from', css_class='form-control', template='crispy_forms/input_without_wrapper.html'),
                layout.HTML('<span class="input-group-addon">to</span>'),
                layout.Field('date_to', css_class='form-control', template='crispy_forms/input_without_wrapper.html'),
                css_class='input-daterange input-group'
            )
        )

    class Meta:
        model = BookingHome
        exclude = ('booking_task', 'status', 'booking_confirmation_url', 'ticket')

abs/booking/forms/insurance.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms import layout

from ..models import Insurance


class InsuranceForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(InsuranceForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = layout.Layout(
            layout.Div(
                layout.Div(
                    'company',
                    css_class='col-4'
                ),
                layout.Div(
                    'policyholder',
                    css_class='col-4'
                ),
                layout.Div(
                    'issue_date',
                    css_class='col-4'
                ),
                css_class='row'
            ),
            layout.Div(
              layout.HTML('Dates*')
            ),
            layout.Div(
                layout.Field('date_from', css_class='form-control', template='crispy_forms/input_without_wrapper.html'),
                layout.HTML('<span class="input-group-addon">to</span>'),
                layout.Field('date_to', css_class='form-control', template='crispy_forms/input_without_wrapper.html'),
                css_class='input-daterange input-group'
            )
        )

    class Meta:
        model = Insurance
        exclude = ('insurance_file', )

abs/booking/forms/klm_flight.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms import layout

from ..models import KLMFlight
from ..booking_registry import bookingRegistry


class KLMFlightForm(forms.ModelForm):
    key_name = forms.ChoiceField(choices=bookingRegistry.as_choices(),
                                 widget=forms.HiddenInput(),
                                 initial='KLM')
    city_from = forms.ChoiceField(choices=(('Москва', 'Москва'), ), initial='Москва')

    def __init__(self, *args, **kwargs):
        super(KLMFlightForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = layout.Layout(
            'key_name',
            layout.Div(
                layout.Div(
                    'city_from',
                    css_class='col-6'
                ),
                layout.Div(
                    'city_to',
                    css_class='col-6'
                ),
                css_class='row'
            ),
            layout.Div(
              layout.HTML('Dates*')
            ),
            layout.Div(
                layout.Field('date_from', css_class='form-control', template='crispy_forms/input_without_wrapper.html'),
                layout.HTML('<span class="input-group-addon">to</span>'),
                layout.Field('date_to', css_class='form-control', template='crispy_forms/input_without_wrapper.html'),
                css_class='input-daterange input-group'
            )
        )

    class Meta:
        model = KLMFlight
        exclude = ('ticket', 'booking_task', 'status')

abs/booking/forms/ostrovok_home.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms import layout

from ..models import OstrovokHome
from ..booking_registry import bookingRegistry


class OstrovokHomeForm(forms.ModelForm):
    key_name = forms.ChoiceField(choices=bookingRegistry.as_choices(),
                                 widget=forms.HiddenInput(),
                                 initial='Ostrovok')

    def __init__(self, *args, **kwargs):
        super(OstrovokHomeForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = layout.Layout(
            'key_name',
            'city',
            layout.Div(
              layout.HTML('Dates*')
            ),
            layout.Div(
                layout.Field('date_from', css_class='form-control', template='crispy_forms/input_without_wrapper.html'),
                layout.HTML('<span class="input-group-addon">to</span>'),
                layout.Field('date_to', css_class='form-control', template='crispy_forms/input_without_wrapper.html'),
                css_class='input-daterange input-group'
            )
        )

    class Meta:
        model = OstrovokHome
        exclude = ('booking_task', 'status', 'booking_confirmation_url', 'booking_print_url')

abs/booking/forms/person.py
import datetime
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms import layout, bootstrap

from ..models import Person


class PersonForm(forms.ModelForm):
    date_of_birth = forms.DateField(required=False, widget=forms.SelectDateWidget(
        years=range(1940, datetime.date.today().year),
        attrs=({'style': 'width: 33%; display: inline-block;'})
    ))

    def __init__(self, *args, **kwargs):
        super(PersonForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = layout.Layout(
            layout.Div(
                layout.Div(
                    'first_name',
                    css_class='col-5'
                ),
                layout.Div(
                    'last_name',
                    css_class='col-5'
                ),
                layout.Div(
                    'gender',
                    css_class='col-2'
                ),
                css_class='row'
            ),
            layout.Div(
                layout.Div(
                    'date_of_birth',
                    css_class='col-5 date_of_birth_row'
                ),
                css_class='row'
            )
        )

    class Meta:
        model = Person
        exclude = ('content_object', 'content_type', 'object_id')

abs/booking/forms/s7_flight.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms import layout

from ..models import S7Flight
from ..booking_registry import bookingRegistry


class S7FlightForm(forms.ModelForm):
    key_name = forms.ChoiceField(choices=bookingRegistry.as_choices(),
                                 widget=forms.HiddenInput(),
                                 initial='S7')
    city_from = forms.ChoiceField(choices=(('Москва', 'Москва'), ), initial='Москва')

    def __init__(self, *args, **kwargs):
        super(S7FlightForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = layout.Layout(
            'key_name',
            layout.Div(
                layout.Div(
                    'city_from',
                    css_class='col-6'
                ),
                layout.Div(
                    'city_to',
                    css_class='col-6'
                ),
                css_class='row'
            ),
            layout.Div(
              layout.HTML('Dates*')
            ),
            layout.Div(
                layout.Field('date_from', css_class='form-control', template='crispy_forms/input_without_wrapper.html'),
                layout.HTML('<span class="input-group-addon">to</span>'),
                layout.Field('date_to', css_class='form-control', template='crispy_forms/input_without_wrapper.html'),
                css_class='input-daterange input-group'
            )
        )

    class Meta:
        model = S7Flight
        exclude = ('ticket', 'booking_task', 'status')

abs/templates/booking/biletix_flight_form.html
{% load i18n %}
{% load crispy_forms_tags %}

<div class="card mb-2">
    <div class="card-header">
        Biletix
    </div>
    <div class="card-body">
        <form data-type="booking_registry">
            {% crispy form %}
        </form>
    </div>
</div>

abs/templates/booking/booking_home_form.html
{% load i18n %}
{% load crispy_forms_tags %}

<div class="card mb-2">
    <div class="card-header">
        Booking
    </div>
    <div class="card-body">
        <form data-type="booking_registry">
            {% crispy form %}
        </form>
    </div>
</div>

abs/templates/booking/booking_tasks.html
{% extends "base.html" %}
{% load static i18n %}

{% block content %}
    <div class="row">
        <div class="col-12 text-right">
            <div class="pt-2">
                <a class="btn btn-success" href="{% url 'booking:create_booking_task' %}">Add task</a>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-12" id="booking-tasks-container"></div>
    </div>
{% endblock content %}

{% block javascript %}
    {{ block.super }}
    <script src="{% static 'js/booking_tasks.js' %}"></script>
{% endblock %}

abs/templates/booking/booking_tasks_table.html
{% load i18n booking_extras %}

{% if booking_objects %}
    {% regroup booking_objects by booking_task as booking_task_list %}
    {% for booking_task in booking_task_list %}
        <div class="card mb-2">
            <div class="card-header">
                Booking task #{{ booking_task.grouper.id }}
                <small class="text-muted">
                  Created at: {{ booking_task.grouper.created_at }}
                  {% if request.user.is_superuser %}User: <a href="{% url 'admin:users_user_change' booking_task.grouper.user.pk %}" target="_blank">{{ booking_task.grouper.user }}</a>{% endif %}
                </small>
            </div>
            <div class="card-body">
                <table class="table">
                    <tbody>
                        {% for booking_obj in booking_task.list %}
                            {% if booking_obj|classname == "Insurance" %}
                                <tr>
                                    <td>{{ booking_obj }}</td>
                                    <td><a href="{% url 'booking:render_insurance_template' booking_obj.pk %}" target="_blank">PDF file</a></td>
                                    <td></td>
                                </tr>
                            {% else %}
                                <tr>
                                    <td>{{ booking_obj.get_html_info|safe }}</td>
                                    <td width="30%">
                                        {% if booking_obj.status == booking_obj.TASK_SUCCESS_STATUS %}
                                            {{ booking_obj.get_results_html_info|safe }}
                                        {% elif booking_obj.status == booking_obj.TASK_FAILED_STATUS %}
                                            {% for task_error in booking_obj.task_errors.all %}
                                                <p>{{ task_error.message }}</p>
                                            {% endfor %}
                                            {% with booking_obj|content_type as ctype %}
                                                <a href="{%  url 'booking:booking_object_task_errors_detail' ctype.pk booking_obj.pk %}" target="_blank">Open details</a>
                                            {% endwith %}
                                        {% endif %}
                                    </td>
                                    <td class="text-right" width="10%">
                                        <span style="width: 100%;" class="badge {{ booking_obj.status|status_badge_css_class }}">{{ booking_obj.get_status_display }}
                                        </span>
                                    </td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% endfor %}
</table>
{% else %}
    <p class="text-center">Here you will see your booking tasks...</p>
{% endif %}

{% if booking_objects.has_other_pages %}
    <div class="row">
        <div class="col-12">
            <nav aria-label="navigation" class="ptb-3">
                <ul class="pagination host-pagination">
                    {% if booking_objects.has_previous %}
                        <li class="page-item">
                            <a href="#" data-page="{{ booking_objects.previous_page_number }}"
                               class="page-link previous">&lsaquo;&lsaquo; {% trans "Previous" %}</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <span class="page-link previous">&lsaquo;&lsaquo; {% trans "Previous" %}</span>
                        </li>
                    {% endif %}

                    {% if booking_objects.number|add:'-4' > 1 %}
                        <li class="page-item"><a href="#" data-page="{{ booking_objects.number|add:'-5' }}"
                                                 class="page-link">&hellip;</a></li>
                    {% endif %}

                    {% for page in booking_objects.paginator.page_range %}
                        {% if page == booking_objects.number %}
                            <li class="page-item active">
                                <span class="page-link">{{ page }}</span>
                            </li>
                        {% elif page > booking_objects.number|add:'-5' and page < booking_objects.number|add:'5' %}
                            <li class="page-item">
                                <a href="#" data-page="{{ page }}" class="page-link">{{ page }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}

                    {% if booking_objects.paginator.num_pages > booking_objects.number|add:'4' %}
                        <li class="page-item"><a href="#" data-page="{{ booking_objects.number|add:'5' }}"
                                                 class="page-link">&hellip;</a></li>
                    {% endif %}

                    {% if booking_objects.has_next %}
                        <li class="page-item">
                            <a href="#" data-page="{{ booking_objects.next_page_number }}"
                               class="page-link previous">›› {% trans "Next" %}</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <span class="page-link next">›› {% trans "Next" %}</span>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
{% endif %}

abs/templates/booking/change_booking_task.html
{% extends "base.html" %}
{% load static i18n %}

{% block content %}
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'booking:booking_tasks' %}">Task list</a></li>
        <li class="breadcrumb-item active" aria-current="page">Add task</li>
      </ol>
    </nav>

    <div class="row" id="main-form-loader" style="display: none;">
        <div class="col-12">
            <div class="loader mx-auto"></div>
            <p class="text-center">
                Submitting data...
            </p>
        </div>
    </div>

    <div class="row" id="main-form-success" style="display: none;">
        <div class="col-12 text-center">
            <img src="{% static "images/checked.png" %}" class="img-responsive">
            <p>
                Success. Redirecting to task list...
            </p>
        </div>
    </div>

    <div id="main-form-wrapper">
        <div class="row">
            <div class="col-12" id="personForms">
            </div>
        </div>
        <div class="row">
            <div class="col-12" id="chainForms">

            </div>
        </div>
        <div class="row">
            <div class="col-12" id="insuranceForms">

            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="float-right mb-4">
                    <div class="loader mx-auto mr-2" id="add-form-loader"></div>
                    <div class="btn-group mr-2">
                        <button class="btn btn-secondary" type="button" id="addPersonButton">
                            Add person
                        </button>
                    </div>
                    <div class="btn-group mr-2">
                        <button class="btn btn-secondary" type="button" id="addInsuranceButton">
                            Add insurance
                        </button>
                    </div>
                    <div class="btn-group mr-2">
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button"
                                    id="addFlightDropdownMenuButton"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Add flight
                            </button>
                            <div class="dropdown-menu" aria-labelledby="addFlightDropdownMenuButton">
                                <a class="dropdown-item" data-val="KLM"
                                   href="#">KLM Royal Dutch Airlines</a>
                                <a class="dropdown-item" data-val="Biletix"
                                   href="#">Biletix</a>
                              <a class="dropdown-item" data-val="S7"
                                   href="#">S7 Airlines</a>
                            </div>
                        </div>
                    </div>
                    <div class="btn-group mr-2">
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button"
                                    id="addHomeDropdownMenuButton"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Add Home
                            </button>
                            <div class="dropdown-menu" aria-labelledby="addHomeDropdownMenuButton">
                                <a class="dropdown-item" data-val="Booking"
                                   href="#">Booking</a>
                                <a class="dropdown-item" data-val="Ostrovok"
                                   href="#">Ostrovok</a>
                            </div>
                        </div>
                    </div>
                    <div class="btn-group">
                        <button class="btn btn-primary" id="submitForm">Submit</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script src="{% static 'js/change_booking_task.js' %}?v=1"></script>
{% endblock %}

abs/templates/booking/insurance_form.html
{% load i18n %}
{% load crispy_forms_tags %}

<div class="card mb-2">
    <div class="card-header">
        Insurance
    </div>
    <div class="card-body">
        <form data-type="insurance">
            {% crispy form %}
        </form>
    </div>
</div>

abs/templates/booking/klm_flight_form.html
{% load i18n %}
{% load crispy_forms_tags %}

<div class="card mb-2">
    <div class="card-header">
        KLM
    </div>
    <div class="card-body">
        <form data-type="booking_registry">
            {% crispy form %}
        </form>
    </div>
</div>

abs/templates/booking/ostrovok_home_form.html
{% load i18n %}
{% load crispy_forms_tags %}

<div class="card mb-2">
    <div class="card-header">
        Ostrovok
    </div>
    <div class="card-body">
        <form data-type="booking_registry">
            {% crispy form %}
        </form>
    </div>
</div>

abs/templates/booking/person_form.html
{% load i18n %}
{% load crispy_forms_tags %}

<div class="card mb-2">
    <div class="card-header">
    </div>
    <div class="card-body">
        <form data-type="person">
            {% crispy form %}
        </form>
    </div>
</div>

abs/templates/booking/s7_flight_form.html
{% load i18n %}
{% load crispy_forms_tags %}

<div class="card mb-2">
    <div class="card-header">
        S7 Airlines
    </div>
    <div class="card-body">
        <form data-type="booking_registry">
            {% crispy form %}
        </form>
    </div>
</div>